#!/usr/bin/env bash
# handoff-index.sh — SessionStart regenerator for the workspace handoff index.
#
# Handoffs are fragmented BY DESIGN: the session-handoff skill writes each one to
# <launch-cwd>/.claude/handoffs/, so a handoff lands in whichever lab (or the workspace
# root, or $HOME) the session was launched from — and .claude/ is globally git-ignored,
# so they are untracked scratch. That locality is good (a lab's handoffs stay with the
# lab) but it scatters them across many dirs. This hook keeps ONE discoverable map at the
# workspace root: .handoff_index, mapping each handoff filename -> its real path.
#
# It is a workspace coordinator file (a dot-file at the root), so it honors the
# "non-dot ⇒ submodule" invariant without an exception. The hook installs globally but is
# a silent no-op off the JangLabs-style workspace: it walks UP from the session cwd to the
# `.claude-workspace` marker (same mechanism as lab-scope.sh) and does nothing if absent.
#
# Cheap: pure shell + find, no Python, no jq dependency. SessionStart fires once per
# session (startup/resume/clear/compact), not per tool call. Writes a file as a side
# effect; emits NO additionalContext. Fails OPEN and silent on every error.
set -u

# --- locate the workspace root by walking up to the marker (silent no-op if not found) ---
# Read cwd from the SessionStart JSON if jq is present; else fall back to $PWD. We avoid a
# hard jq dependency here (unlike memory hooks) because this hook needs no JSON output.
input=$(cat 2>/dev/null || true)
cwd=""
if command -v jq >/dev/null 2>&1 && [ -n "$input" ]; then
  cwd=$(printf '%s' "$input" | jq -r '.cwd // empty' 2>/dev/null || true)
fi
[ -n "$cwd" ] || cwd="${PWD:-}"
[ -n "$cwd" ] || exit 0

root=""
dir=$cwd
while [ -n "$dir" ] && [ "$dir" != "/" ]; do
  if [ -e "$dir/.claude-workspace" ]; then root=$dir; break; fi
  dir=$(dirname -- "$dir")
done
[ -n "$root" ] || exit 0                                   # off-workspace -> nothing to do

index="$root/.handoff_index"
tmp="$index.tmp.$$"

# --- collect handoff files from every place the skill (or legacy convention) puts them ---
# Search roots, in this order: the workspace root's own .claude/handoffs (cross-lab HOs);
# every top-level non-dot child's .claude/handoffs (per-lab scratch) AND legacy handoffs/
# (the cited, tracked design archive in claude/); and ~/.claude/handoffs (sessions launched
# from $HOME). Each candidate dir is optional — missing ones are simply skipped.
emit_dir() {  # $1 = dir to scan, $2 = label for the path shown (already root-relative or ~)
  [ -d "$1" ] || return 0
  # -maxdepth 1: handoffs are flat files in these dirs. Match .md and .jsonl session logs.
  find "$1" -maxdepth 1 -type f \( -name '*.md' -o -name '*.session.jsonl' \) 2>/dev/null
}

{
  printf '# .handoff_index — generated by claude/hooks/handoff-index.sh on SessionStart.\n'
  printf '# Maps each handoff filename to its real location. Do not edit by hand; it is\n'
  printf '# rewritten every session. Handoffs live per-lab in <lab>/.claude/handoffs/\n'
  printf '# (git-ignored scratch); the tracked claude/handoffs/ is a cited design archive.\n'
  printf '#\n'
  printf '# filename\tpath\n'

  # Workspace-root cross-lab handoffs, then each top-level non-dot child, then $HOME.
  {
    emit_dir "$root/.claude/handoffs"
    for child in "$root"/*/; do
      child=${child%/}
      base=$(basename -- "$child")
      case "$base" in .*) continue ;; esac                 # skip dot-dirs (not labs)
      emit_dir "$child/.claude/handoffs"
      emit_dir "$child/handoffs"                            # legacy/tracked archive (e.g. claude/)
    done
    [ -n "${HOME:-}" ] && emit_dir "$HOME/.claude/handoffs"
  } | sort -u | while IFS= read -r f; do
    [ -n "$f" ] || continue
    name=$(basename -- "$f")
    printf '%s\t%s\n' "$name" "$f"
  done | sort -rt "$(printf '\t')" -k1,1 | while IFS="$(printf '\t')" read -r name f; do
    [ -n "$f" ] || continue
    # Show the path workspace-relative when under the root, ~-relative when under $HOME,
    # else absolute. Keeps the index portable across a workspace move/clone.
    case "$f" in
      "$root"/*)        shown=${f#"$root"/} ;;
      "${HOME:-/dev/null}"/*) shown="~/${f#"$HOME"/}" ;;
      *)                shown=$f ;;
    esac
    printf '%s\t%s\n' "$name" "$shown"
  done
} > "$tmp" 2>/dev/null || { rm -f "$tmp" 2>/dev/null; exit 0; }

# Atomic replace (parity with the settings.json jq+mv discipline). mv is atomic within one
# filesystem; the index and its tmp share the workspace root, so this never races a reader
# into a half-written file.
mv -f "$tmp" "$index" 2>/dev/null || rm -f "$tmp" 2>/dev/null
exit 0
